# .ruff.toml
[lint]
select = ["E", "W", "F"]  # Örnek: Python hataları, uyarılar, isimlendirme
ignore = ["E501"]          # Satır uzunluğu uyarısı (black uyumlu değilse)
per-file-ignores = { "__init__.py" = ["F401"] }

[format]
line-length = 88
