# meta.yaml
package:
  name: grikod
  version: "0.0.0"

source:
  path: .
  url: 
  blake2b-256: 

build:
  noarch: python
  script: python -m pip install --ignore-installed .
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python

about:
  home: https://github.com/KuantumBS/grikod
  license: MIT
  summary: 'Binary to Gray code conversion package.'
  description: |
    Binary to Gray code conversion package.
  dev_url: https://github.com/KuantumBS/grikod
  doc_url: https://github.com/KuantumBS/grikod
  doc_source_url: https://github.com/KuantumBS/grikod/blob/main/README.md
