{% set version = "1.0.80" %}

package:
  name: grikod
  version: {{ version }}

source:
  path: src/grikod/  # Doğru kaynak dizinini belirtin
  url: https://files.pythonhosted.org/packages/1f/ca/7e7cf69c185a6b5a58480ac131f25a13ee6ea562ae0676266a9e6e9b0ea4/grikod-1.0.80.tar.gz
  sha256: 6594a62d3186107361c7c734257c4ecabc450b49ce2b2b3d0bb1b23c91bbdd08

build:
  noarch: python  # Bu ayar, paketin tüm Python sürümlerinde çalışmasını sağlar # generic
  script: python -m pip install --ignore-installed .  # veya başka bir kurulum komutu
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python

about:
  home: https://github.com/KuantumBS/grikod
  license: MIT
  summary: 'Binary to Gray code conversion package.'
  description: |
    Binary to Gray code conversion package.
  dev_url: https://github.com/KuantumBS/grikod
  doc_url: https://github.com/KuantumBS/grikod
  doc_source_url: https://github.com/KuantumBS/grikod/blob/main/README.md
