{% set version = "1.1.4" %}

package:
  name: grikod
  version: {{ version }}

source:
  path: src/grikod/  # Yerel kaynak kodunun dizinini belirtin
  url: 
  sha256: 

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: python -m pip install --ignore-installed .
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python

about:
  home: https://github.com/KuantumBS/grikod
  license: MIT
  summary: 'Binary to Gray code conversion package.'
  description: |
    Binary to Gray code conversion package.
  dev_url: https://github.com/KuantumBS/grikod
  doc_url: https://github.com/KuantumBS/grikod
  doc_source_url: https://github.com/KuantumBS/grikod/blob/main/README.md
  
