{% set version = "1.0.8" %}

package:
  name: grikod
  version: {{ version }}

source:
  path: .  # Doğru kaynak dizinini belirtin
  url: 
  sha256: 

build:
  noarch: python  # Bu ayar, paketin tüm Python sürümlerinde çalışmasını sağlar # generic
  script: python -m pip install --no-deps --ignore-installed .  # veya başka bir kurulum komutu
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/KuantumBS/grikod
  license: MIT
  summary: 'Binary to Gray code conversion package.'
  description: |
    Binary to Gray code conversion package.
  dev_url: https://github.com/KuantumBS/grikod
  doc_url: https://github.com/KuantumBS/grikod
  doc_source_url: https://github.com/KuantumBS/grikod/blob/main/README.md

