[workspace]
preview = ["pixi-build"]
authors = ["Mehmet Keçeci <enfo@tuta.io>"]
channels = ["https://prefix.dev/bilgi", "bilgi", "pypi", "https://prefix.dev/conda-forge", "https://conda.modular.com/max-nightly", "conda-forge", "https://repo.prefix.dev/modular-community"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
name = "grikod"
version = "1.1.91"

[package]
name = "grikod"
version = "1.1.91"
license = "MIT"

[dependencies]
python = ">=3.11"
pip = ">=24.0"
numpy = ">=1.24"
cython = ">=3.0"
pytest = "*"

[tasks]
build = "python -m build"
start = "python -c 'import grikod; print(grikod.__version__)'"
install = "pip install -e ."
test = { depends-on = ["install"], cmd = "pytest" }

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.host-dependencies]
python = ">=3.11"
setuptools = ">=84.0.0"
cython = ">=3.0"
pip = "*"
