[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "grikod"
version = "1.0.0"
description = "İkili sayıları Gri Koda çevirir"
authors = ["Mehmet Keçeci <mkececi@yaani.com>"]
readme = "README.md"
repository = "https://github.com/KuantumBS/grikod/"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
