# pyproject.toml

[build-system]
requires = ["setuptools>=84.0.0", "cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grikod"
version = "1.1.7"
description = "Binary to Gray code conversion package for efficient data encoding."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Mehmet Keçeci", email = "enfo@tuta.io"}]
keywords = ["gray", "code", "converter"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = [
    "numpy",
]

# Aşağıdaki bölümleri SİLİN veya devre dışı bırakın (cibuildwheel manylinux için):
# [tool.cibuildwheel] ...

# [tool.setuptools.packages.find]
# include = ["grikod*"]

# [tool.setuptools]
# include-package-data = true

# [tool.setuptools.package-data]
# "*" = ["*.py", "*.pyx", "*.pyi", "*.pyd", "*.so"]  # .pyx ekleyin, kaynak derleme için

[tool.setuptools_scm]
version_file = "grikod/_version.py"
local_scheme = "no-local-version"

[project.urls]
Homepage = "https://github.com/KuantumBS/grikod/"
Documentation = "https://kuantumbs.github.io/grikod/"
Repository = "https://github.com/KuantumBS/grikod/"
Issues = "https://github.com/KuantumBS/grikod/issues"
